/**
 * Kannada names for Bengaluru's localities, wards and police stations.
 *
 * GENERATED — do not edit by hand. Regenerate with:
 *   node scripts/build-kannada-names.mjs <officials.json>
 *
 * Source: bengawalk's city-officials dataset (CC BY 4.0), which carries the
 * government's own Kannada spellings for every ward, zone, corporation and
 * station. This is the Kannada counterpart of tamil-places.ts, and it
 * follows the same rule: a name we cannot verify is returned UNCHANGED
 * rather than transliterated, because a half-right name on a complaint
 * document is worse than an English one that is right.
 *
 * The station suffix is NOT stored here. bengawalk writes it as "ಪಿಎಸ್",
 * which is the letters P-S spelled phonetically rather than the Kannada
 * words; we keep the bare place and append the real term below.
 */

/** Station-name furniture, translated separately from the place. */
const SUFFIX_KN = "ಪೊಲೀಸ್ ಠಾಣೆ";

const PLACES: Record<string, string> = {
  "A Adugodi": "ಎ ಅಡುಗೋಡಿ",
  "A. Narayanapura": "ಎ.ನಾರಾಯಣಪುರ",
  "Abbigere": "ಅಬ್ಬಿಗೇರೆ",
  "Abdul Kalam Nagar": "ಅಬ್ದುಲ್ ಕಲಾಂ ನಗರ",
  "Adi Chunchanagiri Ward": "ಆದಿ ಚುಂಚನಗಿರಿ ವಾರ್ಡ್",
  "Adugodi": "ಆಡುಗೋಡಿ",
  "AECS Layout": "ಎ.ಇ.ಸಿ.ಎಸ್. ಲೇಔಟ್",
  "Aerocity": "ಏರೋಸಿಟಿ",
  "Agara": "ಅಗರ",
  "Agaram": "ಅಗರಂ",
  "Agrahara Dasarahalli": "ಅಗ್ರಹಾರ ದಾಸರಹಳ್ಳಿ",
  "Ambedkarnagar": "ಅಂಬೇಡ್ಕರ್‌ನಗರ",
  "Amrutahalli": "ಅಮೃತಹಳ್ಳಿ",
  "Amruthahalli": "ಅಮೃತಹಳ್ಳಿ",
  "Amruthahally": "ಅಮೃತಹಳ್ಳಿ",
  "Anandapura": "ಆನಂದಪುರ",
  "Andrahalli": "ಆಂಧ್ರಹಳ್ಳಿ",
  "Anekal": "ಆನೇಕಲ್",
  "Anjanapura": "ಅಂಜನಾಪುರ",
  "Annapoorneshwari Nagar": "ಅನ್ನಪೂರ್ಣೇಶ್ವರಿ ನಗರ",
  "Anubhava Nagara": "ಅನುಭವ ನಗರ",
  "Anugondanahalli": "ಅನುಗೊಂಡನಹಳ್ಳಿ",
  "Arakere": "ಅರಕೆರೆ",
  "Aramane Nagara": "ಅರಮನೆ ನಗರ",
  "Aruna Asif Ali Ward": "ಅರುಣಾ ಅಸಿಫ್ ಅಲಿ ವಾರ್ಡ್",
  "Ashok Nagar": "ಅಶೋಕ್ ನಗರ",
  "Ashoka Nagara": "ಅಶೋಕ ನಗರ",
  "Ashoka Pillar": "ಅಶೋಕ ಸ್ತಂಭ",
  "Ashokanagar": "ಅಶೋಕನಗರ",
  "Ashokanagara": "ಅಶೋಕನಗರ",
  "Ashwath Nagar": "ಅಶ್ವತ್ಥ ನಗರ",
  "Attibele": "ಅತ್ತಿಬೆಲೆ",
  "Attigupe": "ಅತ್ತಿಗುಪ್ಪೆ",
  "Attiguppe": "ಅತ್ತಿಗುಪ್ಪೆ",
  "Attur": "ಅಟ್ಟುರ್",
  "Atturu": "ಅಟ್ಟೂರು",
  "Austin Town": "ಆಸ್ಟಿನ್ ಟೌನ್",
  "Avalahalli": "ಆವಲಹಳ್ಳಿ",
  "Avalahally": "ಆವಲಹಳ್ಳಿ",
  "Azad Nagar": "ಆಜಾದ್ ನಗರ",
  "B Venkata Reddy Nagar": "ಬಿ ವೆಂಕಟ ರೆಡ್ಡಿ ನಗರ",
  "Babusab Palya": "ಬಾಬುಸಾಬ್ ಪಾಳ್ಯ",
  "Bagalagunte": "ಬಾಗಲಗುಂಟೆ",
  "Bagalakunte": "ಬಾಗಲಕುಂಟೆ",
  "Bagalgunte": "ಬಾಗಲಗುಂಟೆ",
  "Bagalur": "ಬಾಗಲೂರು",
  "Banasavadi": "ಬಾಣಸವಾಡಿ",
  "Banashankari": "ಬನಶಂಕರಿ",
  "Banashankari Temple ward": "ಬನಶಂಕರಿ ದೇವಸ್ಥಾನ ವಾರ್ಡ್",
  "Banaswadi": "ಬಾಣಸವಾಡಿ",
  "Bande Mutt": "ಬಂಡೆ ಮಠ",
  "Bandepalya": "ಬಂಡೆಪಾಳ್ಯ",
  "Bandi Reddy Circle Ward": "ಬಂಡಿ ರೆಡ್ಡಿ ಸರ್ಕಲ್ ವಾರ್ಡ್",
  "Bangarappa Nagara": "ಬಂಗಾರಪ್ಪ ನಗರ",
  "Bapuji Nagara": "ಬಾಪೂಜಿ ನಗರ",
  "Basavanagudi": "ಬಸವನಗುಡಿ",
  "Basavanapura": "ಬಸವನಪುರ",
  "Basaveshwara Nagar": "ಬಸವೇಶ್ವರ ನಗರ",
  "Basaveshwara Nagara": "ಬಸವೇಶ್ವರ ನಗರ",
  "Begur": "ಬೇಗೂರ್",
  "Beguru": "ಬೇಗೂರು",
  "Belathur": "ಬೇಲಥುರ್",
  "Bellanduru": "ಬೆಳ್ಳಂದೂರು",
  "Benniganahalli": "ಬೆನ್ನಿಗಾನಹಳ್ಳಿ",
  "Bharath Aikya Ward": "ಭಾರತ ಐಕ್ಯ ವಾರ್ಡ್",
  "Bharathi Nagar": "ಭಾರತಿ ನಗರ",
  "Bhattarahalli": "ಭಟ್ಟರಹಳ್ಳಿ",
  "Bheereshwara Nagar": "ಭೀರೇಶ್ವರ ನಗರ",
  "BHEL Ward": "ಭೆಲ್ ವಾರ್ಡ್",
  "Bhoopasandra": "ಭೂಪಸಂದ್ರ",
  "Bhuvaneshwari Nagar": "ಭುವನೇಶ್ವರಿ ನಗರ",
  "Bidadi": "ಬಿಡದಿ",
  "Bilekahalli": "ಬಿಳೇಕಹಳ್ಳಿ",
  "Bilekhalli": "ಬಿಳೇಕಹಳ್ಳಿ",
  "Binnipete": "ಬಿನ್ನಿಪೇಟೆ",
  "Binnypete": "ಬಿನ್ನಿಪೇಟೆ",
  "Bommanahalli": "ಬೊಮ್ಮನಹಳ್ಳಿ",
  "Brundavana Nagara": "ಬೃಂದಾವನ ನಗರ",
  "BTM Layout": "ಬಿ ಟಿ ಎಂ ಲೇಔಟ್",
  "Byadarahalli": "ಬ್ಯಾಡರಹಳ್ಳಿ",
  "Byappanahalli": "ಬೈಯಪ್ಪನಹಳ್ಳಿ",
  "Byatarayanapura": "ಬ್ಯಾಟರಾಯನಪುರ",
  "Byrasandra": "ಬೈರಸಂದ್ರ",
  "Byrathi": "ಬೈರತಿ",
  "C V Raman Nagar": "ಸಿ ವಿ ರಾಮನ್ ನಗರ",
  "C.K.Acchukattu": "ಸಿ.ಕೆ.ಅಚ್ಚುಕಟ್ಟು",
  "Chalavadipalya": "ಚಲವಾದಿಪಾಳ್ಯ",
  "Challakere": "ಚಳ್ಳಕೆರೆ",
  "Chamarajpet": "ಚಾಮರಾಜಪೇಟೆ",
  "Chamrajapet": "ಚಾಮರಾಜಪೇಟೆ",
  "Chamundi Nagara": "ಚಾಮುಂಡಿ ನಗರ",
  "Chandra Layout": "ಚಂದ್ರಾ ಲೇಔಟ್",
  "Chandralayout": "ಚಂದ್ರಾಲೇಔಟ್",
  "Chandranagara": "ಚಂದ್ರನಗರ",
  "Channapatna East": "ಚನ್ನಪಟ್ಟಣ ಪೂರ್ವ",
  "Channapatna Rural": "ಚನ್ನಪಟ್ಟಣ ಗ್ರಾಮಾಂತರ",
  "Channarayapatna": "ಚನ್ನರಾಯಪಟ್ಟಣ",
  "Channasandra": "ಚನ್ನಸಂದ್ರ",
  "Chellakere": "ಚೆಲ್ಲಕೆರೆ",
  "Cheluvadi Palya": "ಚೆಲುವಾಡಿ ಪಾಳ್ಯ",
  "Chickpete": "ಚಿಕ್ಕಪೇಟೆ",
  "Chikka Adugodi": "ಚಿಕ್ಕ ಅಡುಗೋಡಿ",
  "Chikkabanavara": "ಚಿಕ್ಕಬಾಣಾವರ ಪಿ.ಎಸ್",
  "Chikkajala": "ಚಿಕ್ಕಜಾಲ",
  "Chikkalasandra": "ಚಿಕ್ಕಲಸಂದ್ರ",
  "Chikkalsandra": "ಚಿಕ್ಕಲಸಂದ್ರ",
  "Chikkasandra": "ಚಿಕ್ಕಸಂದ್ರ",
  "Chikkathoguru": "ಚಿಕ್ಕಥೋಗೂರು",
  "Chokkasandra": "ಚೊಕ್ಕಸಂದ್ರ",
  "Chowdeshwari Nagar": "ಚೌಡೇಶ್ವರಿ ನಗರ",
  "Chowdeshwari ward": "ಚೌಡೇಶ್ವರಿ ವಾರ್ಡ್",
  "Chowdeswari Ward": "ಚೌಡೇಶ್ವರಿ ವಾರ್ಡ್",
  "City Market": "ಸಿಟಿ ಮಾರ್ಕೆಟ್",
  "Commercial Street": "ಕಮರ್ಷಿಯಲ್ ಸ್ಟ್ರೀಟ್",
  "Cottonpet": "ಕಾಟನ್‌ಪೇಟೆ",
  "Cottonpete": "ಕಾಟನ್ ಪೇಟೆ",
  "Cox Town": "ಕಾಕ್ಸ್ ಟೌನ್",
  "Cubbon Park": "ಕಬ್ಬನ್ ಪಾರ್ಕ್",
  "CV Raman Nagar": "ಸಿವಿ ರಾಮನ್ ನಗರ",
  "D.V Gundappa Ward": "ಡಿ.ವಿ. ಗುಂಡಪ್ಪ ವಾರ್ಡ್",
  "Da.Ra. Bendre Ward": "ದ.ರಾ. ಬೇಂದ್ರೆ ವಾರ್ಡ್",
  "Dasarahalli": "ದಾಸರಹಳ್ಳಿ",
  "Dattatreya Temple": "ದತ್ತಾತ್ರೇಯ ದೇವಸ್ಥಾನ",
  "Dattatreya Ward": "ದತ್ತಾತ್ರೇಯ ವಾರ್ಡ್",
  "Dayanand Nagara": "ದಯಾನಂದ ನಗರ",
  "Dayananda Nagar": "ದಯಾನಂದ ನಗರ",
  "Deepanjali Nagar": "ದೀಪಾಂಜಲಿ ನಗರ",
  "Deepanjali Nagara": "ದೀಪಾಂಜಲಿ ನಗರ",
  "Devagiri Temple Ward": "ದೇವಗಿರಿ ದೇವಸ್ಥಾನ ವಾರ್ಡ್",
  "Devanahalli": "ದೇವನಹಳ್ಳಿ",
  "Devara Jeevanahalli": "ದೇವರ ಜೀವನಹಳ್ಳಿ",
  "Devarachikkanahalli": "ದೇವರಚಿಕ್ಕನಹಳ್ಳಿ",
  "Devaraj Urs Nagar": "ದೇವರಾಜ್ ಅರಸ್ ನಗರ",
  "Devaraj Urs Ward": "ದೇವರಾಜ ಅರಸು ವಾರ್ಡ್",
  "Devarajeevanahalli": "ದೇವಜೀವನಹಳ್ಳಿ",
  "Devasandra": "ದೇವಸಂದ್ರ",
  "Dharmagiri Ward": "ಧರ್ಮಗಿರಿ ವಾರ್ಡ್",
  "Dharmaraya Swamy Temple": "ಧರ್ಮರಾಯ ಸ್ವಾಮಿ ದೇವಸ್ಥಾನ",
  "Dharmaraya Swamy Temple Ward": "ಧರ್ಮರಾಯ ಸ್ವಾಮಿ ದೇವಸ್ಥಾನ ವಾರ್ಡ್",
  "Dinnur": "ದಿನ್ನೂರು",
  "Dobbespet": "ದೊಬ್ಬೆಸಪೇಟೆ",
  "Dodda Bidarakallu": "ದೊಡ್ಡ ಬಿದರಕಲ್ಲು",
  "Dodda Bommasandra": "ದೊಡ್ಡ ಬೊಮ್ಮಸಂದ್ರ",
  "Dodda Ganapati": "ದೊಡ್ಡ ಗಣಪತಿ",
  "Dodda Nekkundi": "ದೊಡ್ಡ ನೆಕ್ಕುಂಡಿ",
  "Doddaballapura Rural": "ದೊಡ್ಡಬಳ್ಳಾಪುರ ಗ್ರಾಮಾಂತರ",
  "Doddaballapura Town": "ದೊಡ್ಡಬಳ್ಳಾಪುರ ಟೌನ್",
  "Doddabelavangala": "ದೊಡ್ಡಬೆಳವಂಗಲ",
  "Doddabettahalli": "ದೋಡ್ಡಬೇಟ್ಟಹಲ್ಲಿ",
  "Doddabommasandra": "ದೊಡ್ಡಬೊಮ್ಮಸಂದ್ರ",
  "Doddakammanahalli": "ದೊಡ್ಡಕಮ್ಮನಹಳ್ಳಿ",
  "Doddanna Nagar": "ದೊಡ್ಡಣ್ಣ ನಗರ",
  "Domlur": "ದೊಮ್ಮಲೂರು",
  "Domluru": "ದೊಮ್ಮಲೂರು",
  "Dooravaninagar": "ದೂರವಾಣಿನಗರ",
  "Doresanipalya": "ದೊರೇಸಾನಿಪಾಳ್ಯ",
  "Dr Rajkumar Ward": "ಡಾ. ರಾಜ್‌ಕುಮಾರ್ ವಾರ್ಡ್",
  "Dr. Puneet Rajkumar": "ಡಾ. ಪುನೀತ್ ರಾಜ್ ಕುಮಾರ್",
  "Dr. Puneeth Rajkumar Ward": "ಡಾ. ಪುನೀತ್ ರಾಜ್‌ಕುಮಾರ್ ವಾರ್ಡ್",
  "Dr. Raj Kumar Agrahara Dasarahalli": "ಡಾ. ರಾಜ್ ಕುಮಾರ್ ಅಗ್ರಹಾರ ದಾಸರಹಳ್ಳಿ",
  "Dr. Vishnuvardhan Ward": "ಡಾ. ವಿಷ್ಣುವರ್ಧನ್ ವಾರ್ಡ್",
  "East": "ಪೂರ್ವ",
  "Ejipura": "ಈಜಿಪುರ",
  "Electronic City": "ಎಲೆಕ್ಟ್ರಾನಿಕ್ ಸಿಟಿ",
  "Freedom Fighter Ward": "ಸ್ವಾತಂತ್ರ್ಯ ಹೋರಾಟಗಾರ ವಾರ್ಡ್",
  "G.M Palya": "ಜಿ.ಎಂ. ಪಾಳ್ಯ",
  "Gali Anjaneya Temple Ward": "ಗಾಲಿ ಆಂಜನೇಯ ದೇವಸ್ಥಾನ ವಾರ್ಡ್",
  "Gandhinagar": "ಗಾಂಧಿನಗರ",
  "Ganesh Mandir ward": "ಗಣೇಶ ಮಂದಿರ ವಾರ್ಡ್",
  "Ganesh Mandira Ward": "ಗಣೇಶ ಮಂದಿರ ವಾರ್ಡ್",
  "Ganga Nagar": "ಗಂಗಾ ನಗರ",
  "Gangammagudi": "ಗಂಗಮ್ಮಗುಡಿ",
  "Ganganagar": "ಗಂಗಾನಗರ",
  "Gangenahalli": "ಗಂಗೇನಹಳ್ಳಿ",
  "Garudachar Palya": "ಗರುಡಾಚಾರ್ ಪಾಳ್ಯ",
  "Garvebavi Palya": "ಗರ್ವೆಬಾವಿ ಪಾಳ್ಯ",
  "Gavi Gangadhareshwara": "ಗವಿ ಗಂಗಾಧರೇಶ್ವರ",
  "Gayathri Nagara": "ಗಾಯತ್ರಿ ನಗರ",
  "Gayithri Nagar": "ಗಾಯಿತ್ರಿ ನಗರ",
  "Geddalahalli": "ಗೆದ್ದಲಹಳ್ಳಿ",
  "Gharebhavipalya": "ಘರೇಭಾವಿಪಾಳ್ಯ",
  "Girinagar": "ಗಿರಿನಗರ",
  "Gopalpura": "ಗೋಪಾಲಪುರ",
  "Goraguntepalya": "ಗೊರಗುಂಟೆಪಾಳ್ಯ",
  "Gottigere": "ಗೊಟ್ಟಿಗೆರೆ",
  "Govindapura": "ಗೋವಿಂದಪುರ ಪಿ.ಎಸ್",
  "Govindaraja Nagar": "ಗೋವಿಂದರಾಜ ನಗರ",
  "Govindarajanagar": "ಗೋವಿಂದರಾಜನಗರ",
  "Gowdanapalya": "ಗೌಡನಪಾಳ್ಯ",
  "Gunjur": "ಗುಂಜೂರು",
  "Gurappanapalya": "ಗುರಪ್ಪನಪಾಳ್ಯ",
  "H.A.L.": "ಎಚ್.ಎ.ಎಲ್.",
  "H.S.R.Layout": "ಎಚ್.ಎಸ್.ಆರ್.ಲೇಔಟ್",
  "Hagaduru": "ಹಗದೂರು",
  "HAL Airport": "HAL ವಿಮಾನ ನಿಲ್ದಾಣ",
  "Halasur": "ಹಲಸೂರು",
  "Halasurgate": "ಹಲಸೂರುಗೇಟ್",
  "Halasuru": "ಹಲಸೂರು",
  "Hampi Nagar": "ಹಂಪಿ ನಗರ",
  "Hanumanthanagar": "ಹನುಮಂತನಗರ",
  "Hanumathanagar": "ಹನುಮತಾನಗರ",
  "Harinagar": "ಹರಿನಗರ",
  "Harohalli": "ಹಾರೋಹಳ್ಳಿ",
  "HBR Layout": "HBR ಲೇಔಟ್",
  "Hebbal": "ಹೆಬ್ಬಾಳ",
  "Hebbal Kempapura": "ಹೆಬ್ಬಾಳ ಕೆಂಪಾಪುರ",
  "Hebbala": "ಹೆಬ್ಬಾಳ",
  "Hegganahalli": "ಹೆಗ್ಗನಹಳ್ಳಿ",
  "Hemmigepura": "ಹೆಮ್ಮಿಗೆಪುರ",
  "Hennur": "ಹೆಣ್ಣೂರು",
  "Herohalli": "ಹೇರೋಹಳ್ಳಿ",
  "High Grounds": "ಹೈ ಗ್ರೌಂಡ್ಸ್",
  "HMT Ward": "ಎಚ್.ಎಂ.ಟಿ. ವಾರ್ಡ್",
  "Hombegowda Nagar": "ಹೊಂಬೇಗೌಡ ನಗರ",
  "Hombegowda Nagara": "ಹೊಂಬೇಗೌಡ ನಗರ",
  "Hongasandra": "ಹೊಂಗಸಂದ್ರ",
  "Hoodi": "ಹೂದಿ",
  "Horamavu": "ಹೊರಮಾವು",
  "Hosa Road": "ಹೊಸ ರಸ್ತೆ",
  "Hosahalli": "ಹೊಸಹಳ್ಳಿ",
  "Hosakerehalli": "ಹೊಸಕೆರೆಹಳ್ಳಿ",
  "Hosakote": "ಹೊಸಕೋಟೆ",
  "Hosapalya": "ಹೊಸಪಾಳ್ಯ",
  "Hoysala Nagar": "ಹೊಯ್ಸಳ ನಗರ",
  "Hoysala Nagara Central": "ಹೊಯ್ಸಳ ನಗರ ಮಧ್ಯ",
  "Hoysala Nagara East": "ಹೊಯ್ಸಳ ನಗರ ಪೂರ್ವ",
  "HRBR Layout": "ಎಚ್.ಆರ್.ಬಿ.ಆರ್. ಬಡಾವಣೆ",
  "HSR Layout": "HSR ಲೇಔಟ್",
  "Hudi": "ಹೂಡಿ",
  "Hulimavu": "ಹುಳಿಮಾವು",
  "Iblur": "ಇಬ್ಳೂರು",
  "Ibluru": "ಇಬ್ಲೂರು",
  "Ijoor": "ಇಜೂರ್",
  "Indiranagar": "ಇಂದಿರಾನಗರ",
  "IPD Salappa Ward": "ಐಪಿಡಿ ಸಾಲಪ್ಪ ವಾರ್ಡ್",
  "Ittamadu": "ಇಟ್ಟಮಡು",
  "J P Nagar": "ಜೆ ಪಿ ನಗರ",
  "J.C. Nagar": "ಜೆ.ಸಿ.ನಗರ",
  "J.P PARK": "ಜೆ.ಪಿ. ಪಾರ್ಕ್",
  "Jagadish Nagar": "ಜಗದೀಶ್ ನಗರ",
  "Jagajeevanram Nagar": "ಜಗಜೀವನರಾಮ್ ನಗರ",
  "Jai Maruthi Nagar": "ಜೈ ಮಾರುತಿ ನಗರ",
  "Jakkasandra": "ಜಕ್ಕಸಂದ್ರ",
  "Jakkur": "ಜಕ್ಕೂರು",
  "Jakkuru": "ಜಕ್ಕೂರು",
  "Jalahalli": "ಜಾಲಹಳ್ಳಿ",
  "Jaraganahalli": "ಜರಗನಹಳ್ಳಿ",
  "Jaya Chamarajendra Nagara": "ಜಯ ಚಾಮರಾಜೇಂದ್ರ ನಗರ",
  "Jayachamarajendra Nagar": "ಜಯಚಾಮರಾಜೇಂದ್ರ ನಗರ",
  "Jayamahal": "ಜಯಮಹಲ್",
  "Jayanagar": "ಜಯನಗರ",
  "Jayanagar East": "ಜಯನಗರ ಪೂರ್ವ",
  "Jayaprakash Nagar": "ಜಯಪ್ರಕಾಶ ನಗರ",
  "Jeevan Bheemanagar": "ಜೀವನ್ ಭೀಮನಗರ",
  "Jeevan Bhimanagar": "ಜೀವನ್ ಭೀಮನಗರ",
  "Jeevanahalli": "ಜೀವನಹಳ್ಳಿ",
  "Jeevanbhima Nagar": "ಜೀವನಭೀಮ ನಗರ",
  "Jigani": "ಜಿಗಣಿ",
  "JJR Nagara": "ಜೆ.ಜೆ.ಆರ್. ನಗರ",
  "Jnana Bharathi ward": "ಜ್ಞಾನ ಭಾರತಿ ವಾರ್ಡ್",
  "Jnanabharathi": "ಜ್ಞಾನಭಾರತಿ",
  "Jogpalya": "ಜೋಗಪಾಳ್ಯ",
  "Jogupalya": "ಜೋಗುಪಾಳ್ಯ",
  "JP Park": "ಜೆಪಿ ಪಾರ್ಕ್",
  "K Chennasandra": "ಕೆ ಚೆನ್ನಸಂದ್ರ",
  "K Kamaraj Ward": "ಕೆ. ಕಾಮರಾಜ್ ವಾರ್ಡ್",
  "K Narayanapura": "ಕೆ ನಾರಾಯಣಪುರ",
  "K R Market": "ಕೆ ಆರ್ ಮಾರುಕಟ್ಟೆ",
  "K R Puram": "ಕೆ ಆರ್ ಪುರಂ",
  "K.G.Halli": "ಕೆ.ಜಿ. ಹಳ್ಳಿ",
  "K.G.Nagar": "ಕೆ.ಜಿ.ನಗರ",
  "K.P Agrahara": "ಕೆ.ಪಿ. ಅಗ್ರಹಾರ",
  "K.R Pura": "ಕೆ.ಆರ್. ಪುರ",
  "K.S. Nissar Ahmed Ward": "ಕೆ.ಎಸ್. ನಿಸಾರ್ ಅಹಮದ್ ವಾರ್ಡ್",
  "Kacharakanahalli": "ಕಾಚರಕನಹಳ್ಳಿ",
  "Kacharkanahalli": "ಕಚರಕನಹಳ್ಳಿ",
  "Kadirenahalli": "ಕಾಡಿರೇನಹಳ್ಳಿ",
  "Kadu Malleshwar Ward": "ಕಾಡು ಮಲ್ಲೇಶ್ವರ ವಾರ್ಡ್",
  "Kadugodi": "ಕಾಡುಗೋಡಿ",
  "Kadugondana Halli": "ಕಾಡುಗೊಂಡನ ಹಳ್ಳಿ",
  "Kadugondanahalli": "ಕಾಡುಗೊಂಡನಹಳ್ಳಿ",
  "Kaggadasanapura": "ಕಗ್ಗದಾಸನಪುರ",
  "Kaggadasapura": "ಕಗ್ಗದಾಸಪುರ",
  "Kaggalipura": "ಕಗ್ಗಲೀಪುರ",
  "Kalasipalya": "ಕಾಳಸಿಪಾಳ್ಯ",
  "Kalena Agrahara": "ಕಾಳೇನ ಅಗ್ರಹಾರ",
  "Kalkere": "ಕಲ್ಕೆರೆ",
  "Kalyan Nagar": "ಕಲ್ಯಾಣ ನಗರ",
  "Kamakshipalya": "ಕಾಮಾಕ್ಷಿಪಾಳ್ಯ",
  "Kamakya Layout": "ಕಾಮಾಕ್ಯ ಬಡಾವಣೆ",
  "Kamalanagara": "ಕಮಲಾನಗರ",
  "Kammagondanahalli": "ಕಮ್ಮಗೊಂಡನಹಳ್ಳಿ",
  "Kammanahalli": "ಕಮ್ಮನಹಳ್ಳಿ",
  "Kanakanapalya": "ಕನಕನಪಾಳ್ಯ",
  "Kanakapura Rural": "ಕನಕಪುರ ಗ್ರಾಮಾಂತರ",
  "Kane Muneshwara Ward": "ಕಾಣೆ ಮುನೇಶ್ವರ ವಾರ್ಡ್",
  "Kasavanahalli": "ಕಸವನಹಳ್ಳಿ",
  "Kasturbha Nagar": "ಕಸ್ತೂರ್ಬಾ ನಗರ",
  "Kasturi Nagar": "ಕಸ್ತೂರಿ ನಗರ",
  "Kathriguppe": "ಕಾತ್ರಿಗುಪ್ಪೆ",
  "Katriguppe": "ಕತ್ರಿಗುಪ್ಪೆ",
  "Kaval Bairasandra": "ಕಾವಲ್ ಬೈರಸಂದ್ರ",
  "Kaval Byrasandra": "ಕಾವಲ್ ಬೈರಸಂದ್ರ",
  "Kaveri Nagara": "ಕಾವೇರಿ ನಗರ",
  "Kaveripura": "ಕಾವೇರಿಪುರ",
  "Kempambudhi Ward": "ಕೆಂಪಾಂಬುಧಿ ವಾರ್ಡ್",
  "Kempapura": "ಕೆಂಪಾಪುರ",
  "Kempapura Agrahara": "ಕೆಂಪಾಪುರ ಅಗ್ರಹಾರ",
  "kempegowda international Airport": "ಕೆಂಪೇಗೌಡ ಅಂತರಾಷ್ಟ್ರೀಯ ವಿಮಾನ ನಿಲ್ದಾಣ",
  "Kempegowda Layout": "ಕೆಂಪೇಗೌಡ ಬಡಾವಣೆ",
  "Kempegowda Ward": "ಕೆಂಪೇಗೌಡ ವಾರ್ಡ್",
  "Kengal Hanumanthaiah South": "ಕೆಂಗಲ್ ಹನುಮಂತಯ್ಯ ದಕ್ಷಿಣ",
  "Kengal Hanumanthaiah West": "ಕೆಂಗಲ್ ಹನುಮಂತಯ್ಯ ಪಶ್ಚಿಮ",
  "Kengeri": "ಕೆಂಗೇರಿ",
  "Kengeri Kote ward": "ಕೆಂಗೇರಿ ಕೋಟೆ ವಾರ್ಡ್",
  "Kethamaranahalli": "ಕೆತ್ತಮಾರನಹಳ್ಳಿ",
  "Kodandarampura": "ಕೋದಂದರಂಪುರ",
  "Kodi Chikkanahalli": "ಕೋಡಿ ಚಿಕ್ಕನಹಳ್ಳಿ",
  "Kodichikkanahalli": "ಕೋಡಿಚಿಕ್ಕನಹಳ್ಳಿ",
  "Kodigehalli": "ಕೊಡಿಗೇಹಳ್ಳಿ",
  "Kodihalli": "ಕೋಡಿಹಳ್ಳಿ",
  "Kogilu": "ಕೋಗಿಲು",
  "Kolala": "ಕೊಳಲ",
  "Konanakunte": "ಕೋಣನಕುಂಟೆ",
  "Konena Agrahara": "ಕೊನೆನ ಅಗ್ರಹಾರ",
  "Koramangala": "ಕೋರಮಂಗಲ",
  "Kormangala East": "ಕೋರಮಂಗಲ ಪೂರ್ವ",
  "Kormangala West": "ಕೋರಮಂಗಲ ಪಶ್ಚಿಮ",
  "Kothanur": "ಕೊತ್ತನೂರು",
  "Kottegepalya": "ಕೊಟ್ಟಿಗೆಪಾಳ್ಯ",
  "Kotthur": "ಕೊತ್ತೂರು",
  "KR Puram": "ಕೆಆರ್ ಪುರ",
  "Krishnadevaraya ward": "ಕೃಷ್ಣದೇವರಾಯ ವಾರ್ಡ್",
  "Krishnaiahnapalya": "ಕೃಷ್ಣಯ್ಯನಪಾಳ್ಯ",
  "Krishnanagar": "ಕೃಷ್ಣನಗರ",
  "Kudlu": "ಕೂಡ್ಲು",
  "Kudur": "ಕುದೂರು",
  "Kumaraswamy Layout": "ಕುಮಾರಸ್ವಾಮಿ ಲೇಔಟ್",
  "Kumbalagudu": "ಕುಂಬಳಗೂಡು",
  "Kundalahalli": "ಕುಂದಲಹಳ್ಳಿ",
  "Kushal Nagar": "ಕುಶಾಲ್ ನಗರ",
  "Kuvempu Nagar": "ಕುವೆಂಪು ನಗರ",
  "Kuvempu Ward": "ಕುವೆಂಪು ವಾರ್ಡ್",
  "Kuvempunagara": "ಕುವೆಂಪುನಗರ",
  "Kyathasadra": "ಕ್ಯಾತಸದ್ರ",
  "L.B Shastri Nagar": "ಎಲ್.ಬಿ. ಶಾಸ್ತ್ರಿ ನಗರ",
  "Laggere": "ಲಗ್ಗೆರೆ",
  "Lakkasandra": "ಲಕ್ಕಸಂದ್ರ",
  "Lakshmi Devi Nagar": "ಲಕ್ಷ್ಮಿ ದೇವಿ ನಗರ",
  "Laxmidevi Nagar": "ಲಕ್ಷ್ಮೀದೇವಿ ನಗರ",
  "Lingadheeranahalli": "ಲಿಂಗಧೀರನಹಳ್ಳಿ",
  "Lingarajapura": "ಲಿಂಗರಾಜಪುರ",
  "Lingarajpura": "ಲಿಂಗರಾಜಪುರ",
  "M.K. Doddi": "ಎಂ.ಕೆ. ದೊಡ್ಡಿ ಪಿ.ಎಸ್",
  "Madhanayakanahally": "ಮಾದನಾಯಕನಹಳ್ಳಿ",
  "Madivala": "ಮಡಿವಾಳ",
  "Madiwala": "ಮಡಿವಾಳ",
  "Magadi": "ಮಾಗಡಿ",
  "Magadi Road": "ಮಾಗಡಿ ರಸ್ತೆ",
  "Mahadevapura": "ಮಹದೇವಪುರ",
  "Mahalakshmi Layout": "ಮಹಾಲಕ್ಷ್ಮಿ ಲೇಔಟ್",
  "Mahalakshmipuram": "ಮಹಾಲಕ್ಷ್ಮೀಪುರಂ",
  "Malathalli": "ಮಳತಳ್ಳಿ",
  "Mallasandra": "ಮಲ್ಲಸಂದ್ರ",
  "Mallathahalli": "ಮಲ್ಲತ್ತಹಳ್ಳಿ",
  "Malleshwaram": "ಮಲ್ಲೇಶ್ವರಂ",
  "Malleshwarm": "ಮಲ್ಲೇಶ್ವರಂ",
  "Malleswaram": "ಮಲ್ಲೇಶ್ವರಂ",
  "Mangammana Palya": "ಮಂಗಮ್ಮನ ಪಾಳ್ಯ",
  "Mangammanapalya": "ಮಂಗಮ್ಮನಪಾಳ್ಯ",
  "Manjunath Nagara": "ಮಂಜುನಾಥ ನಗರ",
  "Manjunatha Nagar": "ಮಂಜುನಾಥ ನಗರ",
  "Manorayanapalya": "ಮನೋರಾಯನಪಾಳ್ಯ",
  "Marathahalli": "ಮಾರತ್ತಹಳ್ಳಿ",
  "Marenahalli": "ಮಾರೇನಹಳ್ಳಿ",
  "Marenahalli South": "ಮಾರೇನಹಳ್ಳಿ ದಕ್ಷಿಣ",
  "Marenahalli West": "ಮಾರೇನಹಳ್ಳಿ ಪಶ್ಚಿಮ",
  "Maruthi Mandir ward": "ಮಾರುತಿ ಮಂದಿರ ವಾರ್ಡ್",
  "Maruthi Mandira Ward": "ಮಾರುತಿ ಮಂದಿರ ವಾರ್ಡ್",
  "Maruthi Seva Nagar": "ಮಾರುತಿ ಸೇವಾ ನಗರ",
  "Maruthi Seva Nagara": "ಮಾರುತಿ ಸೇವಾ ನಗರ",
  "Mathikere": "ಮತ್ತಿಕೆರೆ",
  "Mattikere": "ಮತ್ತಿಕೆರೆ",
  "Mico layout Bangalore": "ಮೈಕೋ ಲೇಔಟ್ ಬೆಂಗಳೂರು",
  "Moodalapalya": "ಮೂಡಲಪಾಳ್ಯ",
  "Mudalapalya": "ಮೂಡಲಪಾಳ್ಯ",
  "Munekollal": "ಮುನೆಕೊಳ್ಳಲ್",
  "Muneshwara Block": "ಮುನೇಶ್ವರ ಬ್ಲಾಕ್",
  "Muneshwara Nagar": "ಮುನೇಶ್ವರ ನಗರ",
  "Munnenkolalu": "ಮುನ್ನೇಕೊಳ್ಳಲು",
  "N.A.L Layout": "ಎನ್.ಎ.ಎಲ್. ಬಡಾವಣೆ",
  "N.R Colony": "ಎನ್.ಆರ್. ಕಾಲೊನಿ",
  "N.S Palya": "ಎನ್.ಎಸ್. ಪಾಳ್ಯ",
  "Nada prabhu Kempegowda Nagara": "ನಾಡಪ್ರಭು ಕೆಂಪೇಗೌಡ ನಗರ",
  "Nagadevanahalli": "ನಾಗದೇವನಹಳ್ಳಿ",
  "Naganathapura": "ನಾಗನಾಥಪುರ",
  "Nagapura": "ನಾಗಾಪುರ",
  "Nagarabhavi": "ನಾಗರಭಾವಿ",
  "Nagarbhavi": "ನಾಗರಭಾವಿ",
  "Nagasandra": "ನಾಗಸಂದ್ರ",
  "Nagashettyhalli": "ನಾಗಶೆಟ್ಟಿಹಳ್ಳಿ",
  "Nagavara": "ನಾಗವಾರ",
  "Nagavarapalya": "ನಾಗವಾರಪಾಳ್ಯ",
  "Nalagadarenahalli": "ನಾಲಗದರೇನಹಳ್ಳಿ",
  "Nalvadi Krishna Raja Wadiyar": "ನಾಲ್ವಡಿ ಕೃಷ್ಣರಾಜ ಒಡೆಯರ್",
  "Nalwadi Krishnaraja Wadiyar Ward": "ನಾಲ್ವಡಿ ಕೃಷ್ಣರಾಜ ಒಡೆಯರ್ ವಾರ್ಡ್",
  "Nandini Layout": "ನಂದಿನಿ ಲೇಔಟ್",
  "National Games Village": "ರಾಷ್ಟ್ರೀಯ ಕ್ರೀಡಾ ಗ್ರಾಮ",
  "Nayanda Halli": "ನಾಯಂದಹಳ್ಳಿ",
  "Nayandahalli": "ನಾಯಂಡಹಳ್ಳಿ",
  "Neelasandra": "ನೀಲಸಂದ್ರ",
  "Nehru Nagar": "ನೆಹರೂ ನಗರ",
  "Nelagadaranahalli": "ನೆಲಗದರನಹಳ್ಳಿ",
  "Nelamangala Rural": "ನೆಲಮಂಗಲ ಗ್ರಾಮಾಂತರ",
  "Nelamangala Town": "ನೆಲಮಂಗಲ ಟೌನ್",
  "Nele Maheshwaramma Temple Ward": "ನೆಲೆ ಮಹೇಶ್ವರಮ್ಮ ದೇವಸ್ಥಾನ ವಾರ್ಡ್",
  "New Guddadahalli": "ಹೊಸ ಗುಡ್ಡದಹಳ್ಳಿ",
  "New Tavarekere": "ಹೊಸ ತಾವರೆಕೆರೆ",
  "New Thippasandra": "ಹೊಸ ತಿಪ್ಪಸಂದ್ರ",
  "New Tippasandara": "ಹೊಸ ತಿಪ್ಪಸಂದರ",
  "Nilasandra": "ನೀಲಸಂದ್ರ",
  "Nyayanga Badavane": "ನ್ಯಾಯಂಗ ಬಡಾವಣೆ",
  "Okalipuram": "ಓಕಳಿಪುರಂ",
  "Old Baiyappanahalli": "ಹಳೆಯ ಬೈಯಪ್ಪನಹಳ್ಳಿ",
  "Old Guddadahalli": "ಹಳೇ ಗುಡ್ಡದಹಳ್ಳಿ",
  "Padarayanapura": "ಪಾದರಾಯನಪುರ",
  "Padmanabha Nagar": "ಪದ್ಮನಾಭ ನಗರ",
  "Padmanabhanagara": "ಪದ್ಮನಾಭನಗರ",
  "Panathur": "ಪಾಣತ್ತೂರು",
  "parappana Agrahara": "ಪರಪ್ಪನ ಅಗ್ರಹಾರ",
  "Parvathi Nagar": "ಪಾರ್ವತಿ ನಗರ",
  "Pattabhirama Nagara": "ಪಟ್ಟಾಭಿರಾಮ ನಗರ",
  "Pattegar Palya": "ಪಟ್ಟೇಗಾರ ಪಾಳ್ಯ",
  "Peenya": "ಪೀಣ್ಯ",
  "Peenya Industrial Area": "ಪೀಣ್ಯ ಕೈಗಾರಿಕಾ ಪ್ರದೇಶ",
  "Periyar Nagar": "ಪೆರಿಯಾರ್ ನಗರ",
  "Prakash Nagara": "ಪ್ರಕಾಶ ನಗರ",
  "Priyadarshini Ward": "ಪ್ರಿಯದರ್ಶಿನಿ ವಾರ್ಡ್",
  "Pulakeshi Nagar": "ಪುಲಕೇಶಿ ನಗರ",
  "Pulakeshinagar": "ಪುಲಕೇಶಿನಗರ",
  "Pulikeshinagar": "ಪುಲಿಕೇಶಿನಗರ",
  "Puttenahalli": "ಪುಟ್ಟೇನಹಳ್ಳಿ",
  "R.T. Nagar": "ಆರ್.ಟಿ. ನಗರ",
  "Radhakrishna Temple Ward": "ರಾಧಾಕೃಷ್ಣ ದೇವಸ್ಥಾನ ವಾರ್ಡ್",
  "Raja Kempegowda ward": "ರಾಜ ಕೆಂಪೇಗೌಡ ವಾರ್ಡ್",
  "Raja Mayura Varma Ward": "ರಾಜ ಮಯೂರ ವರ್ಮ ವಾರ್ಡ್",
  "Rajagopal Nagar": "ರಾಜಗೋಪಾಲ್ ನಗರ",
  "Rajagopala Nagara": "ರಾಜಗೋಪಾಲ ನಗರ",
  "Rajaji Nagar": "ರಾಜಾಜಿ ನಗರ",
  "Rajajinagara": "ರಜಜಿನಗರ",
  "Rajamahal": "ರಾಜಮಹಲ್",
  "Rajamahal Guttahalli": "ರಾಜಮಹಲ್ ಗುಟ್ಟಹಳ್ಳಿ",
  "Rajanukunte": "ರಾಜಾನುಕುಂಟೆ",
  "Rajarajeshwari Nagar": "ರಾಜರಾಜೇಶ್ವರಿ ನಗರ",
  "Rajarajeshwari Nagara": "ರಾಜರಾಜೇಶ್ವರಿ ನಗರ",
  "Rajarajeshwari Temple ward": "ರಾಜರಾಜೇಶ್ವರಿ ದೇವಸ್ಥಾನ ವಾರ್ಡ್",
  "Rajeshwarinagar": "ರಾಜೇಶ್ವರಿನಗರ",
  "Rajgopal Nagar": "ರಾಜಗೋಪಾಲ್ ನಗರ",
  "Rajiv Gandhi Nagar": "ರಾಜೀವ್ ಗಾಂಧಿ ನಗರ",
  "Rajiv Nagar": "ರಾಜೀವ್ ನಗರ",
  "Rama Mandira": "ರಾಮ ಮಂದಿರ",
  "Ramamurthy Nagar": "ರಾಮಮೂರ್ತಿ ನಗರ",
  "Ramamurthy Nagara": "ರಾಮಮೂರ್ತಿ ನಗರ",
  "Ramanagara Rural": "ರಾಮನಗರ ಗ್ರಾಮಾಂತರ",
  "Ramanagara Town": "ರಾಮನಗರ ಟೌನ್",
  "Ramaswamy Palya": "ರಾಮಸ್ವಾಮಿ ಪಾಳ್ಯ",
  "Ramaswamypalya": "ರಾಮಸ್ವಾಮಿಪಾಳ್ಯ",
  "Rayapuram": "ರಾಯಪುರಂ",
  "RBI layout": "RBI ಲೇಔಟ್",
  "RR Nagar": "ಆರ್ ಆರ್ ನಗರ",
  "RR Nagara": "ಆರ್ ಆರ್ ನಾಗರಾ",
  "S K Garden": "ಎಸ್ ಕೆ ಗಾರ್ಡನ್",
  "S.G Palya": "ಎಸ್.ಜಿ. ಪಾಳ್ಯ",
  "S.J. Park": "ಎಸ್.ಜೆ. ಪಾರ್ಕ್",
  "S.M Krishna Ward": "ಎಸ್.ಎಂ. ಕೃಷ್ಣ ವಾರ್ಡ್",
  "Sadashiva Nagara": "ಸದಾಶಿವ ನಗರ",
  "Sadashivanagar": "ಷದಶಿವನಗರ್ Pಷ್",
  "Sagayapuram": "ಸಗಾಯಪುರಂ",
  "Sagayarapuram": "ಸಗಾಯರಪುರಂ",
  "Samadhana Nagar": "ಸಮಾಧಾನ ನಗರ",
  "Sampangiram Nagar": "ಸಂಪಂಗಿರಾಮ್ ನಗರ",
  "Sampangirama Nagar": "ಸಂಪಂಗಿರಾಮ ನಗರ",
  "Sampangiramanagar": "ಸಂಪಂಗಿರಾಮನಗರ",
  "Sampigehalli": "ಸಂಪಿಗೆಹಳ್ಳಿ",
  "Sane Guruvana Halli": "ಸಾಣೆ ಗುರುವನ ಹಳ್ಳಿ",
  "Sangama Ward": "ಸಂಗಮ ವಾರ್ಡ್",
  "Sangolli Rayanna Ward": "ಸಂಗೊಳ್ಳಿ ರಾಯಣ್ಣ ವಾರ್ಡ್",
  "Sanjay Nagara": "ಸಂಜಯ ನಗರ ಪಿ.ಎಸ್",
  "Sanjaya Nagar": "ಸಂಜಯ ನಗರ",
  "Sanjaynagar": "ಸಂಜಯನಗರ",
  "Sarakki": "ಸಾರಕ್ಕಿ",
  "Sarjapura": "ಸರ್ಜಾಪುರ",
  "Sarvabhouma Nagar": "ಸರ್ವಭೌಮ ನಗರ",
  "Seshadripuram": "ಶೇಷಾದ್ರಿಪುರಂ",
  "Shakambari Nagar": "ಶಾಕಾಂಬರಿ ನಗರ",
  "Shakambarinagara": "ಶಾಕಂಬರಿನಗರ",
  "Shakthi Ganapathi Nagar": "ಶಕ್ತಿ ಗಣಪತಿ ನಗರ",
  "Shakthi Ganapathi Nagara": "ಶಕ್ತಿ ಗಣಪತಿ ನಗರ",
  "Shakthi Nagar": "ಶಕ್ತಿ ನಗರ",
  "Shampura": "ಶಂಪುರ",
  "Shankar Matt": "ಶಂಕರ್ ಮಟ್ಟ್",
  "Shankar Mutt": "ಶಂಕರ ಮಠ",
  "Shankarapuram": "ಶಂಕರಪುರಂ",
  "Shanthi Nagar": "ಶಾಂತಿ ನಗರ",
  "Shanthinagar": "ಶಾಂತಿನಗರ",
  "Sheshadripuram": "ಶೇಷಾದ್ರಿಪುರಂ",
  "Shettihalli": "ಶೆಟ್ಟಿಹಳ್ಳಿ",
  "Shidlagatta Rural": "ಶಿಡ್ಲಗಟ್ಟಾ ಗ್ರಾಮಾಂತರ",
  "Shivaji Nagar": "ಶಿವಾಜಿ ನಗರ",
  "Shivajinagar": "ಶಿವಾಜಿನಗರ",
  "Shivanagara": "ಶಿವನಗರ",
  "Shivanapalya": "ಶಿವನಪಾಳ್ಯ",
  "Shivanasamudra Ward": "ಶಿವನಸಮುದ್ರ ವಾರ್ಡ್",
  "Shivapura": "ಶಿವಪುರ",
  "Siddapura": "ಸಿದ್ದಾಪುರ",
  "Silver Jublee Park": "ಸಿಲ್ವರ್ ಜೂಬ್ಲಿ ಪಾರ್ಕ್",
  "SilverJubilee Park Ward": "ಸಿಲ್ವರ್ ಜ್ಯೂಬಿಲೀ ಪಾರ್ಕ್ ವಾರ್ಡ್",
  "Singapura": "ಸಿಂಗಾಪುರ",
  "Singasandra": "ಸಿಂಗಸಂದ್ರ",
  "Soladevanahalli": "ಸೋಲದೇವನಹಳ್ಳಿ",
  "Someshwara Nagara": "ಸೋಮೇಶ್ವರ ನಗರ",
  "Someswara Temple Ward": "ಸೋಮೇಶ್ವರ ದೇವಸ್ಥಾನ ವಾರ್ಡ್",
  "South": "ದಕ್ಷಿಣ",
  "Sri Lakshmi Devi Ward": "ಶ್ರೀ ಲಕ್ಷ್ಮಿ ದೇವಿ ವಾರ್ಡ್",
  "Srigandada Kaval": "ಶ್ರೀಗಂಧದ ಕಾವಲ್",
  "Srigandhadakaval": "ಶ್ರೀಗಂಧದಕಾವಲ್",
  "Srigandhanagar": "ಶ್ರೀಗಂಧನಗರ",
  "Srinagar": "ಶ್ರೀನಗರ",
  "Srinivasa Nagara": "ಶ್ರೀನಿವಾಸ ನಗರ",
  "Sriramamandir": "ಶ್ರೀರಾಮಮಂದಿರ",
  "Srirampura": "ಶ್ರೀರಾಂಪುರ",
  "Subbayanapalya": "ಸುಬ್ಬಯ್ಯನಪಾಳ್ಯ",
  "Subbayyanapalya": "ಸುಬ್ಬಯ್ಯನಪಾಳ್ಯ",
  "Subedarpalya": "ಸುಬೇದಾರ್‌ಪಾಳ್ಯ",
  "Subhash Nagar": "ಸುಭಾಷ್ ನಗರ",
  "Subrahmanyapura": "ಸುಬ್ರಹ್ಮಣ್ಯಪುರ",
  "Subramanya Nagar": "ಸುಬ್ರಹ್ಮಣ್ಯ ನಗರ",
  "Subramanyanagara": "ಸುಬ್ರಮಣ್ಯನಗರ",
  "Subramanyapura": "ಸುಬ್ರಹ್ಮಣ್ಯಪುರ ಪಿ.ಎಸ್",
  "Suddagunte Palya": "ಸುದ್ದಗುಂಟೆ ಪಾಳ್ಯ",
  "Suddaguntepalya": "ಸುದ್ದಗುಂಟೆಪಾಳ್ಯ ಪಿ.ಎಸ್",
  "Sulibele": "ಸೂಲಿಬೆಲೆ",
  "Sunkadakatte": "ಸುಂಕದಕಟ್ಟೆ",
  "Sunkenahalli": "ಸುಂಕೇನಹಳ್ಳಿ",
  "Swamy Vivekananda": "ಸ್ವಾಮಿ ವಿವೇಕಾನಂದ",
  "Swamy Vivekananda Ward": "ಸ್ವಾಮಿ ವಿವೇಕಾನಂದ ವಾರ್ಡ್",
  "Swatantra Palya Ward": "ಸ್ವಾತಂತ್ರ್ಯ ಪಾಳ್ಯ ವಾರ್ಡ್",
  "T Dasarahalli": "ಟಿ ದಾಸರಹಳ್ಳಿ",
  "T.R Shamanna Nagar": "ಟಿ.ಆರ್. ಶಾಮಣ್ಣ ನಗರ",
  "Talagattapura": "ತಲಗಟ್ಟಪುರ",
  "Tavarekere": "ತಾವರೆಕೆರೆ",
  "Thalagattapura": "ತಲಗಟ್ಟಪುರ",
  "Thalaghattapura": "ತಲಘಟ್ಟಪುರ",
  "Thanisandra": "ಥಣಿಸಂದ್ರ",
  "Thimmenahalli": "ತಿಮ್ಮೇನಹಳ್ಳಿ",
  "Thindlu": "ತಿಂಡ್ಲು",
  "Thyagarajnagar": "ತ್ಯಾಗರಾಜನಗರ",
  "Thyamagondlu": "ತ್ಯಾಮಗೊಂಡ್ಲು",
  "Tilak Nagar": "ತಿಲಕ್ ನಗರ",
  "Tilak Nagara": "ತಿಲಕ ನಗರ",
  "Uday Nagar": "ಉದಯ ನಗರ",
  "Ullal": "ಉಳ್ಳಾಲ",
  "Ullalu": "ಉಲ್ಲಾಳು",
  "Ulsoor": "ಹಲಸೂರು",
  "Upparpet": "ಉಪ್ಪಾರಪೇಟೆ",
  "Uttarahalli": "ಉತ್ತರಹಳ್ಳಿ",
  "V.V. Puram": "ವಿ.ವಿ. ಪುರಂ",
  "Vannarpet": "ವನ್ನಾರಪೇಟ್",
  "Varalakshmi Nagar": "ವರಲಕ್ಷ್ಮಿ ನಗರ",
  "Varthur": "ವರ್ತೂರು",
  "Varthuru": "ವರ್ತೂರು",
  "Vasanth Nagar": "ವಸಂತ ನಗರ",
  "Vasanthapura": "ವಸಂತಪುರ",
  "Vasanthnagar": "ವಸಂತನಗರ",
  "Vasanthpura": "ವಸಂತಪುರ",
  "Venkat Reddy Nagara": "ವೆಂಕಟ್ ರೆಡ್ಡಿ ನಗರ",
  "Venkateshpuram": "ವೆಂಕಟೇಶಪುರಂ",
  "Vibhootipura": "ವಿಭೂತಿಪುರ",
  "Vidhana Soudha": "ವಿಧಾನಸೌಧ ಪಿ.ಎಸ್",
  "Vidhyaranyapura": "ವಿದ್ಯಾರಣ್ಯಪುರ",
  "Vidyapeeta ward": "ವಿದ್ಯಾಪೀಠ ವಾರ್ಡ್",
  "Vidyaranyanagara": "ವಿದ್ಯಾರಣ್ಯನಗರ",
  "Vidyaranyapura": "ವಿದ್ಯಾರಣ್ಯಪುರ",
  "Vignananagara": "ವಿಜ್ಞಾನನಗರ",
  "Vijaya Bank Layout": "ವಿಜಯ ಬ್ಯಾಂಕ್ ಬಡಾವಣೆ",
  "Vijayanagar": "ವಿಜಯನಗರ",
  "Vijayapura": "ವಿಜಯಪುರ ಪಿ.ಎಸ್",
  "Vijinapura": "ವಿಜಿನಾಪುರ",
  "Vijnana Nagar": "ವಿಜ್ಞಾನ ನಗರ",
  "Vinayaka Layout": "ವಿನಾಯಕ ಬಡಾವಣೆ",
  "Vinayakanagar": "ವಿನಾಯಕನಗರ",
  "Vishveshwara Puram": "ವಿಶ್ವೇಶ್ವರ ಪುರಂ",
  "Vishwanath Nagenahalli": "ವಿಶ್ವನಾಥ ನಾಗೇನಹಳ್ಳಿ",
  "Vishwanatha Nagenahalli": "ವಿಶ್ವನಾಥ ನಾಗೇನಹಳ್ಳಿ",
  "Vishwanathapura": "ವಿಶ್ವನಾಥಪುರ",
  "Vishwapriya Nagara": "ವಿಶ್ವಪ್ರಿಯ ನಗರ",
  "Viswamanava Kuvempu Ward": "ವಿಶ್ವಮಾನವ ಕುವೆಂಪು ವಾರ್ಡ್",
  "Viveknagar": "ವಿವೇಕನಗರ",
  "Vrisabhavathi Nagar": "ವೃಷಭಾವತಿ ನಗರ",
  "Vrishabhavathi Nagar": "ವೃಷಭಾವತಿ ನಗರ",
  "Vyalikaval": "ವೈಯಾಲಿಕಾವಲ್",
  "West": "ಪಶ್ಚಿಮ",
  "White Field": "ವೈಟ್ ಫೀಲ್ಡ್",
  "Whitefield": "ವೈಟ್‌ಫೀಲ್ಡ್",
  "Wilsongarden": "ವಿಲ್ಸನ್‌ಗಾರ್ಡನ್",
  "Yamalur": "ಯಮಲೂರು",
  "Yarab nagar": "ಯಾರಬ್ ನಗರ",
  "Yediyur": "ಯಡಿಯೂರು",
  "Yediyuru": "ಯಡಿಯೂರು",
  "Yelachenahalli": "ಯಲಚೇನಹಳ್ಳಿ",
  "Yelahanka": "ಯಲಹಂಕ",
  "Yelahanka New Town": "ಯಲಹಂಕ ನ್ಯೂ ಟೌನ್",
  "Yelahanka Satellite Town": "ಯಲಹಂಕ ಸ್ಯಾಟಲೈಟ್ ಟೌನ್",
  "Yelchenahalli": "ಯೆಲ್ಚೇನಹಳ್ಳಿ",
  "Yelenahalli": "ಯಲೇನಹಳ್ಳಿ",
  "Yeshwanthapura": "ಯಶವಂತಪುರ ಪಿ.ಎಸ್",
  "Yeshwanthpura": "ಯಶವಂತಪುರ",
  "Yeshwanthpura RMC Yard": "ಯಶವಂತಪುರ ಆರ್‌ಎಂಸಿ ಯಾರ್ಡ್",
};

/** Municipal bodies, whose full names are translated as a unit. */
const BODIES: Record<string, string> = {
  "Bengaluru Central City Corporation": "ಬೆಂಗಳೂರು ಕೇಂದ್ರ ಮಹಾನಗರ ಪಾಲಿಕೆ",
  "Bengaluru East City Corporation": "ಬೆಂಗಳೂರು ಪೂರ್ವ ನಗರ ಪಾಲಿಕೆ",
  "Bengaluru North City Corporation": "ಬೆಂಗಳೂರು ಉತ್ತರ ನಗರ ಪಾಲಿಕೆ",
  "Bengaluru South City Corporation": "ಬೆಂಗಳೂರು ದಕ್ಷಿಣ ನಗರ ಪಾಲಿಕೆ",
  "Bengaluru West City Corporation": "ಬೆಂಗಳೂರು ಪಶ್ಚಿಮ ನಗರ ಪಾಲಿಕೆ",
};

/** Normalise for lookup: fold case, punctuation and spacing. */
function key(s: string): string {
  return s.toLowerCase().replace(/[.\-_]+/g, " ").replace(/\s+/g, " ").trim();
}

const INDEX = new Map<string, string>(
  Object.entries(PLACES).map(([k, v]) => [key(k), v])
);
const BODY_INDEX = new Map<string, string>(
  Object.entries(BODIES).map(([k, v]) => [key(k), v])
);

/** Kannada for a bare locality or ward, or null when we have no name. */
export function kannadaPlace(name: string): string | null {
  if (!name) return null;
  const bare = name.replace(/^\s*\d+\s*:\s*/, "").replace(/\s*\(\d+\)\s*$/, "");
  return INDEX.get(key(bare)) ?? null;
}

/** Kannada for a municipal body's full name, or null. */
export function kannadaBody(name: string): string | null {
  return name ? BODY_INDEX.get(key(name)) ?? null : null;
}

/**
 * Kannada for a full station name, keeping any beat code.
 *
 * "Adugodi PS" → "ಆಡುಗೋಡಿ ಪೊಲೀಸ್ ಠಾಣೆ". Returns the input untouched when
 * the locality is not in the dictionary.
 */
export function kannadaStation(raw: string): string {
  if (!raw) return raw;
  const m = /^([A-Z]{1,2}\s?\d+[A-Z]?)[.\s]+(.*)$/.exec(raw.trim());
  const code = m ? m[1].replace(/\s+/g, "") : "";
  let rest = (m ? m[2] : raw).trim();
  let hadSuffix = false;
  rest = rest
    .replace(/\s*(Aw\.?P\.?S\.?|P\.?S\.?|Police Station)\s*$/i, () => {
      hadSuffix = true;
      return "";
    })
    .trim();
  const kn = kannadaPlace(rest);
  if (!kn) return raw;
  return [code, kn, hadSuffix ? SUFFIX_KN : ""].filter(Boolean).join(" ");
}
